apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ovn-kubernetes-mcp

resources:
- namespace.yaml
- service-account.yaml
- rbac.yaml
- deployment.yaml
- service.yaml
- networkpolicy.yaml

labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    app.kubernetes.io/component: mcp-server
    app.kubernetes.io/name: ovn-kubernetes-mcp

images:
- name: localhost/ovnk-mcp-server
  newName: localhost/ovnk-mcp-server
  newTag: dev
